version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y unzip wget
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip -d /usr/local/bin
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Running Terraform Validate..."
      - terraform validate
      - echo "Running Terraform Plan..."
      - terraform plan -out=tfplan

artifacts:
  files:
    - tfplan
    - terraform.tfstate
  discard-paths: yes
