version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform on Amazon Linux"
      - export release=amazonlinux
      - sudo dnf install -y dnf-plugins-core
      - sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/${release}/hashicorp.repo
      - sudo dnf install -y terraform
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Formatting Terraform files"
      - terraform fmt -write=true
      - echo "Validating Terraform files"
      - terraform validate
      - echo "Generating Terraform plan"
      - terraform plan -input=false -out=tfplan

artifacts:
  files:
    - tfplan
    - '**/*.tf'
