version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform_1.9.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo "Applying Terraform Plan"
      - terraform init
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - "**/*"
